export const PATH_API = {
    LINK_SIGN: '/api/Users/signup',
    LINK_LOGIN: '/api/Users/signin',
    LINK_PROFILE: '/api/Users/TestToken',
    LINK_CATEGORY_PROJECT: '/api/ProjectCategory',
    LINK_CREATE_PROJECT: '/api/Project/createProjectAuthorize',
    LINK_GET_ALL_PROJECT: '/api/Project/getAllProject',
    LINK_EDIT_PROJECT: '/api/Project/updateProject',
    LINK_DELETE_PROJECT: '/api/Project/deleteProject',
    LINK_GET_USERS: '/api/Users/getUser',
    LINK_ADD_USER_PROJECT: '/api/Project/assignUserProject',
    LINK_REMOVE_USER_FROM_PROJECT: '/api/Project/removeUserFromProject',
    LINK_TEST_TOKEN: '/api/Users/TestToken',
    LINK_TASK_TYPE: '/api/TaskType/getAll',
    LINK_GET_PRIORITY: '/api/Priority/getAll',
    LINK_CREATE_TASK: '/api/Project/createTask',
    LINK_GET_STATUS: '/api/Status/getAll',
    LINK_GET_PROJECT_ID: '/api/Users/getUserByProjectId',
    LINK_TASK_DETAIL: '/api/Project/getTaskDetail',
    LINK_UPDATE_TASK: '/api/Project/updateTask',
    LINK_UPDATE_STATUS:'/api/Project/updateStatus',
}